### ISSUE TITLE
A few issues from the review

### ISSUE THREAD

**Issue by robinwhittleton** [picklefactory/p-g-wodehouse_the-coming-of-bill#1]
Really nice production, just a few things left to tackle.

general:
- `typogrify` makes a couple of reasonable changes
- we leave out the word “Chapter” from headings; see https://standardebooks.org/manual/1.8.0/single-page#8.1.4 . That means that the `epub:type="ordinal z3998:roman"` can be applied directly to the `h3`. Hopefully this should be easy enough with a find and replace.
- Once that’s done you can rebuild the page titles with `se build-title .`
- Then the ToC needs to be regenerated with `se build-toc .`. This also introduces the correct ToC indentation for the book / chapter model.
- Commits that fix transcription issues aren’t `[Editorial]` changes, and we should remove this from the commit messages. How do you feel about rebasing?

content.opf:
- description: `hygeine` -> `hygiene`
- longdesc: `hygeine` -> `hygiene`
- longdesc: can we add something about this work specifically? At the moment it’s just about Wodehouse.
- The artist `file-as` is different to the normal name. Typically we’d have the `file-as` as just being a rearrangement of the normal name. So here I’d expect it to be “McInnes, W. Beckwith”. You can always add a `full-name` entry with William included.

chapter-1-1:
- Agreed that the question-mark should be inside the italics, but then we need to get the linter to ignore it. You can do this with an `se-lint-ignore.xml` file in the root of the project. More info at https://standardebooks.org/manual/1.8.0/single-page#2.3

chapter-1-12:
- A couple of base italics. I think I’d probably remove them in an `[Editorial]` commit? They’re not referencing the works the characters appear in as far as I can tell.

colophon:
- `L.` needs an `<abbr epub:type="z3998:given-name">`
- `Alex Krieger` needs to be wrapped in a `<b epub:type="z3998:personal-name">`

**Comment by picklefactory** [comment]
Here I thought I had done good work eliminating some typos from the text, only to introduce a couple of my own in the longdesc!

I have accomplished a rebase or two in the past, and the commit history here is very straightforward. I'll rebase and force push to fix the Editorial commit messages (fingers crossed) and then tackle the rest.

Thanks very much!

**Comment by picklefactory** [comment]
Rebase done with reworded commit messages. I will update the thread again when I've taken care of the rest.

**Comment by picklefactory** [comment]
OK. All updates complete, and in my environment `se lint .` returns clean.

**Comment by robinwhittleton** [comment]
Looks good! Couple more minor things:

- `Munsey’s Magazine` (in the longdesc) needs italics: https://standardebooks.org/manual/1.8.0/single-page#8.2.11.2
- `W.` in the colophon needs an `<abbr epub:type="z3998:given-name">`

**Comment by picklefactory** [comment]
OK, done!
